package Logica;
import Excepciones.*;
import LogicaDTO.*;
import java.util.List;
import java.util.Set;
import javax.swing.tree.DefaultMutableTreeNode;

public interface IControllerMusica { 
    public abstract void altaAlbum(DtoAlbum album, Set<DtoTema> temas) throws AlbumYaExisteException, UsuarioNoExisteException;   
    public abstract void AltaGenero (String nombregen, String nombrepadre) throws GenroYaExiste;
    public abstract void altaListaReproduccion(String nombre, String genero, String duenio, String ruta, boolean privada)throws ListaYaExisteException, GeneroNoExiste;
    public void publicarLista(String nombreUsuario, String nombreLista) throws UsuarioNoExisteException, ListaNoexisteException, OperacionNoPermitidaException, ListaYaEsPublicaException;
    //public abstract void AgregarTemaLista(String nombreusuario,String nombrelista, String nombretema)throws UsuariosNoExisten, ListaNoexisteException,NoesDueñodelaLista, TemaNoExiste;
    public abstract DefaultMutableTreeNode DameTodoslosgeneros();
    public abstract void EliminoGenero(String nombregen);
    public abstract List<String> obtenerAlbumsPorGenero(String generoSeleccionado);
    public abstract List<String> obtenerAlbumsPorArtista(String artistaSeleccionado);
    public abstract DtoAlbum consultaAlbumPorTitulo(String albumSeleccionado);
    public abstract boolean existeAlbum(String nicknameArtista, String titulo);
    public  abstract List <DtoGenero> Datageneros();
    public  abstract void AñadotemalistaAlbum(String nombreAlbum, String nombreLista, String nombreTema, String NombreUsuario);
    public abstract void aniadoTemaListaPublica(String nombreLista, String nombreTema,String nombreAlbum);
    public abstract List <DtoTema> TemasdeListas(String nombrelista);
    public abstract List<DtoLista> Obtengolistas()throws NoExisteLista;
    public abstract List<DtoLista> Obtengolistassinduenio()throws NoExisteLista;
    public abstract void aniadoTemaListaConduenio(String nombreUsuario,String nombrelista,String nombreteam,String nombreAlbum);
    public abstract List<DtoLista> Obtengolistasconduenio()throws NoExisteLista;
    public abstract List<DtoAlbum> ObtengoAlbums();
    public abstract List<DtoTema> ObtengoTemasdeAlbum(String nombreAlbum);
    public abstract void EliminotemaLista(String nombrelista, String nombretema, String nombreAlbum);
    public abstract void EliminoTemaListaConduenio(String nombreUsuario,String nombrelista,String nombreteam,String nombreAlbum);
    public abstract List<DtoTema> obtenerTemitas();
    public abstract List<DtoTema> obtenerTemitasDATA();
    public abstract List<DtoLista> ObtengoListasPublicas() throws NoExisteLista;
    public abstract List<DtoAlbum> obtenerAlbums();
    public abstract DtoLista consultaListaPorTituloyGenero(String listaSeleccionada, String genero);
    public abstract List<DtoTema> obtenerTemitasfavCliente(String nicknames);
    public abstract List<DtoLista> obtenerListitasfavCliente(String nicknames);
    public abstract List<DtoAlbum> obtenerAlbumsfavCliente(String nicknames);
    public abstract List<String> obtenerListaPorGenero(String generoSeleccionado);
    public abstract List<DtoLista> obtenerListaPorClienteDATA(String artistaSeleccionado);
    public abstract List<String> obtenerListaPorCliente(String artistaSeleccionado);
    public abstract DtoLista consultaListaPorTitulo(String listaSeleccionado);
    public abstract List<DtoLista> obtenerListitas();
    public abstract DtoTema consultaTemaPorTitulo(String temaSeleccionada);
    public abstract void aniadoTemaListaConduenioLista(String nombreUsuario,String nombrelista,String nombreteam,String nombrealb);
    public abstract void aniadoTemaListaPublicaLista(String nombrelista,String nombreteam,String nombrealb);
    public abstract List<DtoLista> obtenerListaPorGeneroDTOLISTA(String generoSeleccionado);
    public abstract List <DtoTema> TemasdeListasDTO(String nombrelista);
    public abstract List<DtoLista> ObtengoListasPublicasDATA() throws NoExisteLista;
    public abstract DtoLista ObtenerListaporTitulo(String nombrelista)throws NoExisteLista;
    public abstract DtoTema consultaTemaPorTituloYAlbum(String nombreTema, String nombreAlbum, String nombreArtista);
    public abstract List<String> obtenerNombresGeneros();
    public abstract List<DtoAlbum> obtenerTodosLosAlbums();
    public abstract boolean albumEsDeXGenero(String albumTitulo, String artistaNickname, String generoNombre);
    public abstract List<DtoTema> temasDelAlbum(String titulo);
    public abstract List<String> ObtengolistasClipriv(String nickcli)throws NoExisteLista;
    public abstract List<DtoLista> obtenerListaPorCliPRIVADAS(String Cliente);
    public abstract boolean temaValido(Tema t);
    public abstract boolean existeGenero(String genero);
    public abstract boolean obtenerPadre(String nombreGenero);
    public abstract boolean espublicasiono(String nombreUsuario, String NombreLista);
    public abstract boolean sumaDescarga(DtoTema t);
    public abstract boolean sumaReproduccion(DtoTema t);
    public abstract List<DtoTema> promedioTemas(); 
    public abstract List<DtoAlbum> buscarAlbums(String query);
    public abstract List<DtoLista> buscarListas(String query);
    public abstract List<DtoTema> buscarTemas(String query);
    public abstract String obtengoAlbumDelTema(String tema);
}
